version: '3.3'
services:
 jenkins:
    image: trion/jenkins-docker-client
    privileged: true
    hostname: jenkins
    ports:
        - 8081:8080
        - 50000:50000
       
    volumes:
        - "jenkins_home_volume:/mnt/sda1/var/lib/docker/volumes/jenkins_home_volume/_data"
  
volumes:
    jenkins_home_volume: